### ISSUE TITLE
Image tools example does not work

### ISSUE THREAD

**Issue by r12s** [tinymce/tinymce-docs#212]
The image tools functionality in the image tools example does not work. The toolbar loads but clicking on flip, rotate, edit image buttons produces no result. 

https://beta.tinymce.com/docs/demo/image-tools/
http://codepen.io/tinymce/pen/epbRwB

**Comment by tim-thatcher** [comment]
@Afraithe @kilianc Hey guys, it's not good that the demo of one of our latest features is broken.  How do we get this corrected?  cc: @androb

**Comment by Afraithe** [comment]
As console says, CORS blocked.

Cachefly need to add CORS headers for beta.tinymce.com only tinymce.com/www.tinymce.com is added. This is a manual process, I believe you need to file a support request with Cachefly.

All these domains really screw things up.

**Comment by Afraithe** [comment]
If you look at the image tools example on the demo page, it loads the image from beta.tinymce.com, why are we crossreferencing stuff like this? It makes things a complete mess.

**Comment by kilianc** [comment]
@Afraithe mostly due to the domain switch, we are going through all codepens and live demo to use proper urls, don't be mad at us! :v:

**Comment by Afraithe** [comment]
Wouldn't it be an idea to use relative urls where possible?

**Comment by kilianc** [comment]
@Afraithe of course, that wasn't possible due to local vs beta vs old domain. I am fixing everything up as it should be!

**Comment by Afraithe** [comment]
Alright, cool.

**Comment by kilianc** [comment]
Ok so, turns out @Afraithe was referring to the codepens, all website examples are correctly working already and using relative paths. I need to enable CORS for codepen and that should fix it all.

**Comment by kilianc** [comment]
fixed :beers: :beers:

**Comment by androb** [comment]
Is this fixed?

I am still seeing error on Codepen at http://codepen.io/tinymce/pen/epbRwB

![image](https://cloud.githubusercontent.com/assets/2160304/11380925/dc7976c0-92ad-11e5-9b5b-4d4111414e97.png)

**Comment by kilianc** [comment]
@androb that's because only `https://s.codepen.io` is allowed not `http://s.codepen.io` I can htt later just to make sure, but the embedded version works.

**Comment by Afraithe** [comment]
On the website, it works on the husky image, but not on the tinymce logo image. The sources are from the same domain though... could it be the @ sign in the filename that causes issues?

**Comment by androb** [comment]
When I load it from https://codepen.io/tinymce/pen/epbRwB it still doesn't work. I get the following:

XMLHttpRequest cannot load https://www.tinymce.com/images/glyph-tinymce@2x.png. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://s.codepen.io' is therefore not allowed access.

**Comment by kilianc** [comment]
```
$ curl -I https://www.tinymce.com/images/glyph-tinymce@2x.png

HTTP/1.1 200 OK
Content-Type: image/png
Content-Length: 3726
Connection: keep-alive
Access-Control-Allow-Origin: https://s.codepen.io
Cache-Control: max-age=604800
Cache-Control: public
Date: Tue, 24 Nov 2015 21:32:03 GMT
ETag: "8a73d27405e80b89bce547e4c02db7ed"
Expires: Tue, 01 Dec 2015 21:32:03 GMT
Last-Modified: Thu, 12 Nov 2015 19:34:02 GMT
Server: nginx/1.4.6 (Ubuntu)
X-Cache: Miss from cloudfront
Via: 1.1 815c19cc61c2c75b289d427bf3208431.cloudfront.net (CloudFront)
X-Amz-Cf-Id: G_GT38G1OgTcQfdVBFddagfqm5aDK7qUZMAtm5NXzfCqr2ZfsHUX2w==
```

It's caching let's give it a sec, it's probably caching headers, we can invalidate cloudfront if you want.

**Comment by androb** [comment]
Okay okay I'll be patient :P

**Comment by kilianc** [comment]
So it turns out there is a problem somewhere:

```
curl -I 'https://www.tinymce.com/images/glyph-tinymce@2x.png' \
  -H 'Pragma: no-cache' \
  -H 'Origin: https://s.codepen.io' \
  -H 'Accept-Encoding: gzip, deflate, sdch' \
  -H 'Accept-Language: en-US,en;q=0.8' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36' \
  -H 'Accept: */*' \
  -H 'Referer: https://s.codepen.io/tinymce/fullembedgrid/epbRwB?type=embed&animations=run' \
  -H 'Connection: keep-alive' \
  -H 'Cache-Control: no-cache'

HTTP/1.1 200 OK
Content-Type: image/png
Content-Length: 3726
Connection: keep-alive
Cache-Control: max-age=604800
Cache-Control: public
Date: Tue, 24 Nov 2015 12:09:48 GMT
ETag: "8a73d27405e80b89bce547e4c02db7ed"
Expires: Tue, 01 Dec 2015 12:09:48 GMT
Last-Modified: Thu, 12 Nov 2015 19:34:02 GMT
Server: nginx/1.4.6 (Ubuntu)
X-Cache: RefreshHit from cloudfront
Via: 1.1 77d972a817f766906c971bd07fc786b7.cloudfront.net (CloudFront)
X-Amz-Cf-Id: QrzX8QvUOi3COnRo7rbN9gSoBfbx76jTHegXwu3VjIbiw4SB_WhnbQ==
```

Access-Control-Allow-Origin is not there

**Comment by Afraithe** [comment]
Don't really know how this is setup (never used cloudfront before), but is that cause we are getting a refresh hit from Cloudfront, and not the actual tinymce.com server?

X-Cache: RefreshHit from cloudfront

**Comment by kilianc** [comment]
`X-Cache` just tells you if the file is coming from cloudfront cache or your origin server, valuse are Refresh or Miss or Hit

**Comment by kilianc** [comment]
There something going on with CF.

if you do:

```
curl -I 'http://production.tinymce.com/images/glyph-tinymce@2x.png' \
  -H 'Pragma: no-cache' \
  -H 'Origin: https://s.codepen.io' \
  -H 'Accept-Encoding: gzip, deflate, sdch' \
  -H 'Accept-Language: en-US,en;q=0.8' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36' \
  -H 'Accept: */*' \
  -H 'Referer: https://s.codepen.io/tinymce/fullembedgrid/epbRwB?type=embed&animations=run' \
  -H 'Connection: keep-alive' \
  -H 'Cache-Control: no-cache'
```

you get

```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: https://s.codepen.io
Cache-Control: max-age=604800
Cache-Control: public
Content-Length: 3726
Content-Type: image/png
Date: Wed, 25 Nov 2015 00:04:03 GMT
ETag: "8a73d27405e80b89bce547e4c02db7ed"
Expires: Wed, 02 Dec 2015 00:04:03 GMT
Last-Modified: Thu, 12 Nov 2015 19:34:02 GMT
Server: nginx/1.4.6 (Ubuntu)
Connection: keep-alive
```

Stil digging

**Comment by kilianc** [comment]
![](https://www.dropbox.com/s/jqeexkrpd2jc1ho/Screenshot%202015-11-24%2017.58.40.png?dl=1)

:beers: for days.
